/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import classes.MSSQLConnection;
import static classes.AppInit.*;
import java.util.ArrayList;
import java.util.List;
import javafx.scene.control.Button;
import javafx.scene.image.Image;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.EnginesEnum.Engines;

/**
 *
 * @author jsarnowski
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {       
        initComponents();
        dbEngineSelect.setModel(new DefaultComboBoxModel(Engines.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        ServerSelectionLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Login = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        ServerSelection = new javax.swing.JComboBox<>();
        CustomPort = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        RememberLogin = new javax.swing.JCheckBox();
        LoginButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        dbEngineSelect = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universal Database Manager");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("LoginFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));

        LoginPanel.setBorder(new javax.swing.border.MatteBorder(null));
        LoginPanel.setNextFocusableComponent(Login);
        LoginPanel.setPreferredSize(new java.awt.Dimension(600, 500));

        LoginLabel.setText("Login");

        PasswordLabel.setText("Password");

        ServerSelectionLabel.setText("Server name/IP address");

        jLabel4.setText("Custom port");

        ServerSelection.setEditable(true);
        ServerSelection.setToolTipText("");

        RememberLogin.setText("Remember me");

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        dbEngineSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dbEngineSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbEngineSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(LoginButton)
                .addGap(18, 18, 18)
                .addComponent(ExitButton)
                .addGap(229, 229, 229))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(RememberLogin))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ServerSelectionLabel)
                            .addComponent(LoginLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(34, 34, 34)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dbEngineSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Password, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CustomPort, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Login, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ServerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbEngineSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginLabel)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServerSelectionLabel)
                    .addComponent(ServerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CustomPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(RememberLogin)
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(ExitButton))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        LoginLabel.getAccessibleContext().setAccessibleDescription("");
        LoginButton.getAccessibleContext().setAccessibleName("LoginButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LoginPanel.getAccessibleContext().setAccessibleName("LoginPanel");

        getAccessibleContext().setAccessibleName("LoginFrame");
        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        try {
            String pwd = new String(Password.getPassword());
            String selectedEngine=dbEngineSelect.getSelectedItem().toString();
            if(selectedEngine==Engines.MSSQL.toString()){
                if(CustomPort.getText() == null || CustomPort.getText().trim().isEmpty()) {
                    appInit.mssqlConnection.DatabaseUserAuthentication(Login.getText(), pwd, ServerSelection.getSelectedItem().toString(), 1433);    
                }
                else {
                    appInit.mssqlConnection.DatabaseUserAuthentication(Login.getText(), pwd, ServerSelection.getSelectedItem().toString(), Integer.parseInt(CustomPort.getText()));
                }

                //this.setVisible(false);
                appInit.engine=selectedEngine;

                if(appInit.mssqlConnection.connection.isClosed() != true) {
                  appInit.tableSelectFrame=new TableSelectFrame();
                  appInit.tableSelectFrame.setSize(400,400);
                  appInit.tableSelectFrame.setResizable(false);
                  appInit.tableSelectFrame.setVisible(true);
                  this.setVisible(false);    
                }
            }
            else if(selectedEngine==Engines.MySQL.toString()){
                if(CustomPort.getText() == null || CustomPort.getText().trim().isEmpty()) {
                    appInit.mysqlConnection.DatabaseUserAuthentication(Login.getText(), pwd, ServerSelection.getSelectedItem().toString(), 3306, "mysql");
                }
                else {
                    appInit.mysqlConnection.DatabaseUserAuthentication(Login.getText(), pwd, ServerSelection.getSelectedItem().toString(), Integer.parseInt(CustomPort.getText()), "mysql");
                }
           // this.setVisible(false);
                appInit.engine=selectedEngine;
                if(appInit.mysqlConnection.connection.isClosed() != true) {
                   appInit.tableSelectFrame=new TableSelectFrame();
                   appInit.tableSelectFrame.setSize(400,400);
                   appInit.tableSelectFrame.setResizable(false);
                   appInit.tableSelectFrame.setVisible(true);   
                 }
                }
            else
                JOptionPane.showMessageDialog(null, "Wybierz silnik bazodanowy"); 
        }
        catch(Exception e) {
            System.out.println("LoginButtonActionPerformed method execution - FAILURE\n" + e);
        }

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        try {
            if(appInit.mssqlConnection.connection.isClosed() == false) {
                appInit.mssqlConnection.connection.close();
            }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void dbEngineSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbEngineSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbEngineSelectActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustomPort;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JCheckBox RememberLogin;
    private javax.swing.JComboBox<String> ServerSelection;
    private javax.swing.JLabel ServerSelectionLabel;
    private javax.swing.JComboBox<String> dbEngineSelect;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
