/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;


import classes.Transactions;
import static classes.Main.*;
import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListModel;
/**
 *
 * @author jsarnowski
 */
public class TableOverviewFrame extends javax.swing.JFrame {

    private String currentDb;
    private String currentTable;

    /**
     * Creates new form TableOverviewFrame
     */
    public TableOverviewFrame(String dbName,String tableName) {
        initComponents();
        this.currentDb=dbName;
        this.currentTable=tableName;
        setLocationRelativeTo(null);
        this.setTitle("Universal Database Manager");
        main.transactions.GetTables();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        TableListPane = new javax.swing.JPanel();
        TableListScrollPane = new javax.swing.JScrollPane();
        TableList = new javax.swing.JTable();
        TableElementDetailsPane = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LogoutMenuButton = new javax.swing.JMenuItem();
        ExitMenuButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setLocation(new java.awt.Point(1, 1));
        setMinimumSize(new java.awt.Dimension(1280, 1024));
        setName("TableOverviewFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 1024));
        setSize(new java.awt.Dimension(1280, 1024));

        TableListPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TableListScrollPane.setBorder(null);

        TableList.setAutoCreateRowSorter(true);
        TableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableList.setColumnSelectionAllowed(true);
        TableListScrollPane.setViewportView(TableList);

        javax.swing.GroupLayout TableListPaneLayout = new javax.swing.GroupLayout(TableListPane);
        TableListPane.setLayout(TableListPaneLayout);
        TableListPaneLayout.setHorizontalGroup(
            TableListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TableListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        TableListPaneLayout.setVerticalGroup(
            TableListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TableListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        TableListScrollPane.getAccessibleContext().setAccessibleName("TableListScrollPane");
        TableListScrollPane.getAccessibleContext().setAccessibleDescription("");

        TableElementDetailsPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout TableElementDetailsPaneLayout = new javax.swing.GroupLayout(TableElementDetailsPane);
        TableElementDetailsPane.setLayout(TableElementDetailsPaneLayout);
        TableElementDetailsPaneLayout.setHorizontalGroup(
            TableElementDetailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        TableElementDetailsPaneLayout.setVerticalGroup(
            TableElementDetailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        LogoutMenuButton.setText("Logout");
        LogoutMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutMenuButtonActionPerformed(evt);
            }
        });
        jMenu1.add(LogoutMenuButton);

        ExitMenuButton.setText("Exit");
        ExitMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuButtonActionPerformed(evt);
            }
        });
        jMenu1.add(ExitMenuButton);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TableListPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TableElementDetailsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TableListPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TableElementDetailsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuButtonActionPerformed
        try {
            if(main.databaseConnection.connection.isClosed() != true) {
                main.databaseConnection.connection.close();
            }
            this.setVisible(false);
            main.loginFrame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TableOverviewFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_ExitMenuButtonActionPerformed

    private void LogoutMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutMenuButtonActionPerformed
        try {
            if(main.databaseConnection.connection.isClosed() != true) {
                main.databaseConnection.connection.close();
            }
            this.setVisible(false);
            main.loginFrame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TableOverviewFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LogoutMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableOverviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableOverviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableOverviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableOverviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitMenuButton;
    private javax.swing.JMenuItem LogoutMenuButton;
    private javax.swing.JPanel TableElementDetailsPane;
    private javax.swing.JTable TableList;
    private javax.swing.JPanel TableListPane;
    private javax.swing.JScrollPane TableListScrollPane;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
